version: '3'
services:
  dynamodb:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: dynamodb
    ports:
      - "7777:7777"
    command: "-inMemory -sharedDb -port 7777"
